In [43]:
function [L,U] = LU(A)
    n = length(A);
    L = eye(n);
    U = zeros(n);
    for r = 1:n
        L(r,1:r-1)
        U(1:r-1,r:n)
        U(r,r:n) = A(r,r:n) - L(r,1:r-1)*U(1:r-1,r:n);
        L(r+1:n,r) = (A(r+1:n,r) - L(r+1:n,1:r-1)*U(1:r-1,r))/U(r,r);
    end
endfunction

In [1]:
A = [10 -7 0 1;-3 2.099999 6 2;5 -1 5 -1;2 1 0 2]

A =

   10.00000   -7.00000    0.00000    1.00000
   -3.00000    2.10000    6.00000    2.00000
    5.00000   -1.00000    5.00000   -1.00000
    2.00000    1.00000    0.00000    2.00000



In [44]:
[L,U]=LU(A);

ans = [](1x0)
ans = [](0x4)
ans = -0.30000
ans =

  -7   0   1

ans =

         0.50000  -2499999.99965

ans =

   0.00000   1.00000
   6.00000   2.30000

ans =

         0.20000  -2399999.99966         0.96000

ans =

         1.00000
         2.30000
   5749998.49920



In [27]:
L,U

L =

         1.00000         0.00000         0.00000         0.00000
        -0.30000         1.00000         0.00000         0.00000
         0.50000  -2499999.99965         1.00000         0.00000
         0.20000  -2399999.99966         0.96000         1.00000

U =

         10.00000         -7.00000          0.00000          1.00000
          0.00000         -0.00000          6.00000          2.30000
          0.00000          0.00000   15000004.99790    5749998.49920
          0.00000          0.00000          0.00000          5.08000



In [85]:
function x = LinearSolveWithLU(L,U,b)
    n = length(b);
    y = zeros(n,1);
    for i = 1:n   
        y(i) = b(i)-L(i,1:i-1)*y(1:i-1);
    end
    x = zeros(n,1);
    for i = n:-1:1
        x(i) = (y(i)-U(i,i+1:n)*x(i+1:n))/U(i,i);
    end
endfunction

In [72]:
b = [8;5.900001;5;1]

b =

   8.0000
   5.9000
   5.0000
   1.0000



In [86]:
x = LinearSolveWithLU(L,U,b)

x =

  -0.00000000060339
  -1.00000000088818
   1.00000000007028
   0.99999999981667

