In [1]:
function [L,U] = LU(A)
    n = length(A);
    L = eye(n);
    U = zeros(n);
    for r = 1:n
        U(r,r:n) = A(r,r:n) - L(r,1:r-1)*U(1:r-1,r:n);
        L(r+1:n,r) = (A(r+1:n,r) - L(r+1:n,1:r-1)*U(1:r-1,r))/U(r,r);
    end
endfunction

In [2]:
A = [1 2 3;2 5 2;3 1 5]

A =

   1   2   3
   2   5   2
   3   1   5



In [3]:
[L,U]=LU(A);

In [4]:
L,U

L =

   1   0   0
   2   1   0
   3  -5   1

U =

    1    2    3
    0    1   -4
    0    0  -24

