In [1]:
import numpy as np
from numpy.linalg import det

from functools import reduce

In [2]:
def LU(A:np.ndarray):
    assert A.ndim == 2
    n = A.shape[0]
    assert n == A.shape[1]
    L = np.eye(n,n)
    U = np.zeros((n,n))
    for r in range(n):
        U[r,r:n] = A[r,r:n] - L[r,0:r]@U[0:r,r:n]
        L[r+1:n,r] = (A[r+1:n,r] -L[r+1:n,0:r]@U[0:r,r])/U[r,r]
    return L,U

In [3]:
A = np.array([
        [10,-7,0,1],
        [-3,2.099999,6,2],
        [5,-1,5,-1],
        [2,1,0,2]
    ])
A

array([[10.      , -7.      ,  0.      ,  1.      ],
       [-3.      ,  2.099999,  6.      ,  2.      ],
       [ 5.      , -1.      ,  5.      , -1.      ],
       [ 2.      ,  1.      ,  0.      ,  2.      ]])

In [4]:
L,U=LU(A)

In [5]:
L

array([[ 1.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
       [-3.0000000e-01,  1.0000000e+00,  0.0000000e+00,  0.0000000e+00],
       [ 5.0000000e-01, -2.5000000e+06,  1.0000000e+00,  0.0000000e+00],
       [ 2.0000000e-01, -2.4000000e+06,  9.5999968e-01,  1.0000000e+00]])

In [6]:
U

array([[ 1.00000000e+01, -7.00000000e+00,  0.00000000e+00,
         1.00000000e+00],
       [ 0.00000000e+00, -1.00000000e-06,  6.00000000e+00,
         2.30000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.50000050e+07,
         5.74999850e+06],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         5.07999891e+00]])