In [10]:
using LinearAlgebra,TimeIt

eye(n) = Matrix{Float64}(I,n,n);

In [2]:
function LU(A)
    n = size(A)[1]
    L = eye(n)
    U = zeros(n,n)
    U[1,1:n] = A[1,1:n]
    L[2:n,1] = A[2:n,1]/U[1,1]
    for r = 2:n
        U[r:r,r:n] = A[r:r,r:n] - L[r:r,1:r-1]*U[1:r-1,r:n]
        if r < n
            L[r+1:n,r:r] = (A[r+1:n,r:r] - L[r+1:n,1:r-1]*U[1:r-1,r:r])/U[r,r]
        end   
    end
    return L,U
end;

In [3]:
A = [1 2 3;2 5 2;3 1 5]

3×3 Array{Int64,2}:
 1  2  3
 2  5  2
 3  1  5

In [13]:
@timeit L,U=LU(A);

1 loops, best of 3: 2.28 µs per loop


In [5]:
L

3×3 Array{Float64,2}:
 1.0   0.0  0.0
 2.0   1.0  0.0
 3.0  -5.0  1.0

In [6]:
U

3×3 Array{Float64,2}:
 1.0  2.0    3.0
 0.0  1.0   -4.0
 0.0  0.0  -24.0